title: "Jinone"
author: "Jinone"
description: "one sample blog"

permalink: /:title/
lang: "en"
paginate: 10 
date_format: "%B %d, %Y"

# Layout

sidebar: false                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: false       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # minima-inspired style without box-shadows

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
  - {title: Twitter, icon: envelope, url: "https://twitter.com/jinonehk"}
  - {title: Hackerone, icon: github, url: "https://hackerone.com/jin0ne"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
comments:
#  disqus: ""                # see https://disqus.com/
#  isso: ""                  # see https://posativ.org/isso/
remote_theme: niklasbuschmann/contrast@v2.4

plugins: 
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout

theme: jekyll-theme-architect
