title: "Jinone"
author: "Jinone"
description: "one sample blog"

permalink: /:title/
lang: "en"
paginate: 10 
date_format: "%B %d, %Y"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # minima-inspired style without box-shadows

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  twitter: "https://twitter.com/jinonehk"
  hackerrank: "https://hackerone.com/jin0ne"
  rss: "/feed.xml"

comments:
#  disqus: ""                # see https://disqus.com/
#  isso: ""                  # see https://posativ.org/isso/

plugins:
 - jekyll-feed
